### ISSUE TITLE
global name 'i' is not defined

### ISSUE THREAD

**Issue by cueneythizli** [EventMiner/EventMiner#2]
There seems to be a problem in the event_extraction.py file.

When I for example try to call "http://localhost:5000/extraction?title=Syrian_Civil_War" I get this error:
"global name 'i' is not defined". I also tried to copy and paste the article into a txt file, to extract it manually with the "test_start_extraction" function. But it's also crashing.

The complete error:

_"Traceback (most recent call last):
  File "run_extraction.py", line 39, in <module>
    test_start_extraction()
  File "run_extraction.py", line 30, in test_start_extraction
    e.start_extraction()
  File "/home/cueneythizli/EventMiner/eventminer/event/event.py", line 54, in start_extraction
    resultset = event_extraction.extract_event(sentence, Event.definitions, event_counter)
  File "/home/cueneythizli/EventMiner/eventminer/event/event_extraction.py", line 126, in extract_event
    detect_time_range_after_keyword(definitions, resultset, sentence, time_index, time_index_2)
  File "/home/cueneythizli/EventMiner/eventminer/event/event_extraction.py", line 192, in detect_time_range_after_keyword
    resultset["end_month"] = definitions["months"][sentence.words[i].string.lower()]
NameError: global name 'i' is not defined
"_

Most of the other wikipedia articles are working fine

**Comment by cueneythizli** [comment]
Ok I'm sorry.
With your new changes in the event_extraction.py file, this bug is fixed
